---
- name: Configure OPS445 CentOS VM
  hosts: vmlab
  become: yes
  vars:
    seneca_id: "rghorsaini"
    ssh_key_path: "/home/rghorsaini/ops445/lab8/keys/authorized_keys"
    lab_dirs:
      - lab1
      - lab2
      - lab3
      - lab4
      - lab5
      - lab6
      - lab7
      - lab8
  tasks:
    - name: Ensure Apache is updated
      yum:
        name: httpd
        state: latest

    - name: Install EPEL repository
      yum:
        name: epel-release
        state: present

    - name: Remove 'tree' package
      yum:
        name: tree
        state: absent

    - name: Set hostname
      hostname:
        name: "{{ seneca_id }}"

    - name: Create user
      user:
        name: "{{ seneca_id }}"
        groups: wheel
        shell: /bin/bash
        state: present

    - name: Create .ssh directory
      file:
        path: "/home/{{ seneca_id }}/.ssh"
        state: directory
        owner: "{{ seneca_id }}"
        group: "{{ seneca_id }}"
        mode: '0700'

    - name: Copy authorized_keys to new user
      copy:
        src: "{{ ssh_key_path }}"
        dest: "/home/{{ seneca_id }}/.ssh/authorized_keys"
        owner: "{{ seneca_id }}"
        group: "{{ seneca_id }}"
        mode: '0600'

    - name: Create lab directories
      file:
        path: "/home/{{ seneca_id }}/ops445/{{ item }}"
        state: directory
        owner: "{{ seneca_id }}"
        group: "{{ seneca_id }}"
        mode: '0755'
      loop: "{{ lab_dirs }}"
